name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Deploy to Railway
        uses: railwayapp/railway-action@master
        with:
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_id: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          service_id: ${{ secrets.RAILWAY_BACKEND_SERVICE_ID }}
          token: ${{ secrets.RAILWAY_TOKEN }}
